In [1]:
import pandas as pd

In [19]:
db_beer = pd.read_csv('data/beer-in-a-neighbourhood-pub.csv')
print(db_beer)

    price  canonical city               country                region  \
0    11.4           Dubai  United Arab Emirates          Middle east
1     9.8            Oslo                Norway               Europe
2     8.5      Copenhagen               Denmark               Europe
3     8.2       Hong Kong             Hong Kong       Asia & Pacific
4     8.1       Singapore             Singapore       Asia & Pacific
5     7.7       Manhattan         United States        North America
6     7.5           Paris                France               Europe
7     7.2   San Francisco         United States        North America
8     7.2          Boston         United States        North America
9     7.1        Helsinki               Finland               Europe
10    7.1          Zurich           Switzerland               Europe
11    7.0          London        United Kingdom               Europe
12    6.8        Shanghai                 China       Asia & Pacific
13    6.7          Dublin               Ireland               Europe
14    6.6        Auckland           New Zealand       Asia & Pacific
15    6.6         Chicago         United States        North America
16    6.5           Milan                 Italy               Europe
17    6.4       Stockholm                Sweden               Europe
18    6.3       Melbourne             Australia       Asia & Pacific
19    6.3          Sydney             Australia       Asia & Pacific
20    5.8           Dhaka            Bangladesh       Asia & Pacific
21    5.7       Edinburgh        United Kingdom               Europe
22    5.6            Rome                 Italy               Europe
23    5.3         Toronto                Canada        North America
24    5.3    Kuala Lumpur              Malaysia       Asia & Pacific
25    5.3      Wellington           New Zealand       Asia & Pacific
26    5.2          Athens                Greece               Europe
27    5.1          Madrid                 Spain               Europe
28    5.0       Vancouver                Canada        North America
29    5.0       Amsterdam           Netherlands               Europe
30    5.0           Tokyo                 Japan       Asia & Pacific
31    5.0         Jakarta             Indonesia       Asia & Pacific
32    4.7          Moscow                Russia               Europe
33    4.5       Frankfurt               Germany               Europe
34    4.3          Vienna               Austria               Europe
35    4.3       New Delhi                 India       Asia & Pacific
36    4.2       Bangalore                 India       Asia & Pacific
37    4.1        Brussels               Belgium               Europe
38    4.0           Seoul          Korea, South       Asia & Pacific
39    3.6          Mumbai                 India       Asia & Pacific
40    3.5       Sao Paulo                Brazil  South/Latin America
41    3.5          Berlin               Germany               Europe
42    3.2        Istanbul                Turkey               Europe
43    3.1     Mexico City                Mexico  South/Latin America
44    2.8  Rio de Janeiro                Brazil  South/Latin America
45    2.6          Warsaw                Poland               Europe
46    2.3    Buenos Aires             Argentina  South/Latin America
47    2.2       Cape Town          South Africa               Africa
48    2.2           Cairo                 Egypt          Middle east
49    2.1    Johannesburg          South Africa               Africa
50    2.0          Lisbon              Portugal               Europe
51    1.9           Lagos               Nigeria               Africa
52    1.9          Manila           Philippines       Asia & Pacific
53    1.6          Prague               Czechia               Europe

    latitude  longitude  population
0    25.2697    55.3094     2502715
1    59.9111    10.7528      693494
2    55.6786    12.5635     1085000
3    22.3050   114.1850     7347000
4     1.3000   103.8000     5745000
5    40.7834   -73.9662     1628706
6    48.8566     2.3522    11020000
7    37.7562  -122.4430     3592294
8    42.3188   -71.0846     4688346
9    60.1756    24.9342      642045
10   47.3786     8.5400      434008
11   51.5072    -0.1275    10979000
12   31.1667   121.4667    22120000
13   53.3425    -6.2658     1173179
14  -36.8500   174.7833     1467800
15   41.8373   -87.6862     8604203
16   45.4669     9.1900     1351562
17   59.3294    18.0686      972647
18  -37.8136   144.9631     5078193
19  -33.8650   151.2094     5312163
20   23.7161    90.3961    15443000
21   55.9530    -3.1890      488050
22   41.8931    12.4828     2872800
23   43.7417   -79.3733     5429524
24    3.1478   101.6953     8285000
25  -41.2889   174.7772      418500
26   37.9794    23.7161      664046
27   40.4189    -3.6919     3266126
28   49.2500  -123.1000     2264823
29   52.3500     4.9166     1031000
30   35.6897   139.6922    37977000
31   -6.2146   106.8451    34540000
32   55.7558    37.6178    17125000
33   50.1136     8.6797      753056
34   48.2083    16.3731     1840573
35   28.7000    77.2000      142004
36   12.9699    77.5980    13707000
37   50.8467     4.3517      185103
38   37.5833   127.0000    21794000
39   18.9667    72.8333    23355000
40  -23.5504   -46.6339    22046000
41   52.5167    13.3833     3644826
42   41.0100    28.9603    15154000
43   19.4333   -99.1333    20996000
44  -22.9083   -43.1964    12272000
45   52.2167    21.0333     1790658
46  -34.5997   -58.3819    16157000
47  -33.9250    18.4250      433688
48   30.0561    31.2394    19372000
49  -26.2044    28.0416     4434827
50   38.7452    -9.1604      506654
51    6.4500     3.4000    15279000
52   14.5958   120.9772    23088000
53   50.0833    14.4167     1324277

In [20]:
db_cappuccino = pd.read_csv('data/cappuccino.csv')
print(db_cappuccino)

    price  canonical city               country                region  \
0     6.3      Copenhagen               Denmark               Europe
1     6.0           Dubai  United Arab Emirates          Middle east
2     5.7       Hong Kong             Hong Kong       Asia & Pacific
3     5.5            Oslo                Norway               Europe
4     5.5           Paris                France               Europe
5     5.4       Singapore             Singapore       Asia & Pacific
6     5.3        Shanghai                 China       Asia & Pacific
7     5.2          Boston         United States        North America
8     5.1          Zurich           Switzerland               Europe
9     5.0        Helsinki               Finland               Europe
10    5.0       Manhattan         United States        North America
11    4.9         Chicago         United States        North America
12    4.8   San Francisco         United States        North America
13    4.5           Seoul          Korea, South       Asia & Pacific
14    4.5           Lagos               Nigeria               Africa
15    4.5           Dhaka            Bangladesh       Asia & Pacific
16    4.2           Tokyo                 Japan       Asia & Pacific
17    4.1          London        United Kingdom               Europe
18    4.1          Vienna               Austria               Europe
19    4.1       New Delhi                 India       Asia & Pacific
20    4.0          Athens                Greece               Europe
21    4.0       Amsterdam           Netherlands               Europe
22    4.0       Stockholm                Sweden               Europe
23    4.0         Jakarta             Indonesia       Asia & Pacific
24    3.9        Brussels               Belgium               Europe
25    3.9    Kuala Lumpur              Malaysia       Asia & Pacific
26    3.9         Toronto                Canada        North America
27    3.9       Vancouver                Canada        North America
28    3.7       Edinburgh        United Kingdom               Europe
29    3.7          Dublin               Ireland               Europe
30    3.6          Mumbai                 India       Asia & Pacific
31    3.6          Moscow                Russia               Europe
32    3.5       Frankfurt               Germany               Europe
33    3.4          Warsaw                Poland               Europe
34    3.3          Berlin               Germany               Europe
35    3.1          Sydney             Australia       Asia & Pacific
36    3.0        Auckland           New Zealand       Asia & Pacific
37    3.0      Wellington           New Zealand       Asia & Pacific
38    3.0     Mexico City                Mexico  South/Latin America
39    3.0          Manila           Philippines       Asia & Pacific
40    3.0       Bangalore                 India       Asia & Pacific
41    3.0       Melbourne             Australia       Asia & Pacific
42    2.7          Prague               Czechia               Europe
43    2.7          Lisbon              Portugal               Europe
44    2.7          Madrid                 Spain               Europe
45    2.3           Cairo                 Egypt          Middle east
46    2.3       Sao Paulo                Brazil  South/Latin America
47    2.3  Rio de Janeiro                Brazil  South/Latin America
48    2.2        Istanbul                Turkey               Europe
49    2.1    Johannesburg          South Africa               Africa
50    2.1       Cape Town          South Africa               Africa
51    2.0            Rome                 Italy               Europe
52    1.9    Buenos Aires             Argentina  South/Latin America
53    1.7           Milan                 Italy               Europe

    latitude  longitude  population
0    55.6786    12.5635     1085000
1    25.2697    55.3094     2502715
2    22.3050   114.1850     7347000
3    59.9111    10.7528      693494
4    48.8566     2.3522    11020000
5     1.3000   103.8000     5745000
6    31.1667   121.4667    22120000
7    42.3188   -71.0846     4688346
8    47.3786     8.5400      434008
9    60.1756    24.9342      642045
10   40.7834   -73.9662     1628706
11   41.8373   -87.6862     8604203
12   37.7562  -122.4430     3592294
13   37.5833   127.0000    21794000
14    6.4500     3.4000    15279000
15   23.7161    90.3961    15443000
16   35.6897   139.6922    37977000
17   51.5072    -0.1275    10979000
18   48.2083    16.3731     1840573
19   28.7000    77.2000      142004
20   37.9794    23.7161      664046
21   52.3500     4.9166     1031000
22   59.3294    18.0686      972647
23   -6.2146   106.8451    34540000
24   50.8467     4.3517      185103
25    3.1478   101.6953     8285000
26   43.7417   -79.3733     5429524
27   49.2500  -123.1000     2264823
28   55.9530    -3.1890      488050
29   53.3425    -6.2658     1173179
30   18.9667    72.8333    23355000
31   55.7558    37.6178    17125000
32   50.1136     8.6797      753056
33   52.2167    21.0333     1790658
34   52.5167    13.3833     3644826
35  -33.8650   151.2094     5312163
36  -36.8500   174.7833     1467800
37  -41.2889   174.7772      418500
38   19.4333   -99.1333    20996000
39   14.5958   120.9772    23088000
40   12.9699    77.5980    13707000
41  -37.8136   144.9631     5078193
42   50.0833    14.4167     1324277
43   38.7452    -9.1604      506654
44   40.4189    -3.6919     3266126
45   30.0561    31.2394    19372000
46  -23.5504   -46.6339    22046000
47  -22.9083   -43.1964    12272000
48   41.0100    28.9603    15154000
49  -26.2044    28.0416     4434827
50  -33.9250    18.4250      433688
51   41.8931    12.4828     2872800
52  -34.5997   -58.3819    16157000
53   45.4669     9.1900     1351562