In [1]:
import pandas as pd

In [5]:
db_beer = pd.read_csv('data/beer-in-a-neighbourhood-pub.csv')
db_beer.set_index('canonical city')

,price,country,region,latitude,longitude,population
canonical city,,,,,,
Dubai,11.4,United Arab Emirates,Middle east,25.2697,55.3094,2502715
Oslo,9.8,Norway,Europe,59.9111,10.7528,693494
Copenhagen,8.5,Denmark,Europe,55.6786,12.5635,1085000
Hong Kong,8.2,Hong Kong,Asia & Pacific,22.3050,114.1850,7347000
Singapore,8.1,Singapore,Asia & Pacific,1.3000,103.8000,5745000
Manhattan,7.7,United States,North America,40.7834,-73.9662,1628706
Paris,7.5,France,Europe,48.8566,2.3522,11020000
San Francisco,7.2,United States,North America,37.7562,-122.4430,3592294
Boston,7.2,United States,North America,42.3188,-71.0846,4688346
Helsinki,7.1,Finland,Europe,60.1756,24.9342,642045
Zurich,7.1,Switzerland,Europe,47.3786,8.5400,434008
London,7.0,United Kingdom,Europe,51.5072,-0.1275,10979000
Shanghai,6.8,China,Asia & Pacific,31.1667,121.4667,22120000
Dublin,6.7,Ireland,Europe,53.3425,-6.2658,1173179
Auckland,6.6,New Zealand,Asia & Pacific,-36.8500,174.7833,1467800
Chicago,6.6,United States,North America,41.8373,-87.6862,8604203
Milan,6.5,Italy,Europe,45.4669,9.1900,1351562
Stockholm,6.4,Sweden,Europe,59.3294,18.0686,972647
Melbourne,6.3,Australia,Asia & Pacific,-37.8136,144.9631,5078193
Sydney,6.3,Australia,Asia & Pacific,-33.8650,151.2094,5312163
Dhaka,5.8,Bangladesh,Asia & Pacific,23.7161,90.3961,15443000
Edinburgh,5.7,United Kingdom,Europe,55.9530,-3.1890,488050
Rome,5.6,Italy,Europe,41.8931,12.4828,2872800
Toronto,5.3,Canada,North America,43.7417,-79.3733,5429524
Kuala Lumpur,5.3,Malaysia,Asia & Pacific,3.1478,101.6953,8285000
Wellington,5.3,New Zealand,Asia & Pacific,-41.2889,174.7772,418500
Athens,5.2,Greece,Europe,37.9794,23.7161,664046
Madrid,5.1,Spain,Europe,40.4189,-3.6919,3266126
Vancouver,5.0,Canada,North America,49.2500,-123.1000,2264823
Amsterdam,5.0,Netherlands,Europe,52.3500,4.9166,1031000
Tokyo,5.0,Japan,Asia & Pacific,35.6897,139.6922,37977000
Jakarta,5.0,Indonesia,Asia & Pacific,-6.2146,106.8451,34540000
Moscow,4.7,Russia,Europe,55.7558,37.6178,17125000
Frankfurt,4.5,Germany,Europe,50.1136,8.6797,753056
Vienna,4.3,Austria,Europe,48.2083,16.3731,1840573
New Delhi,4.3,India,Asia & Pacific,28.7000,77.2000,142004
Bangalore,4.2,India,Asia & Pacific,12.9699,77.5980,13707000
Brussels,4.1,Belgium,Europe,50.8467,4.3517,185103
Seoul,4.0,"Korea, South",Asia & Pacific,37.5833,127.0000,21794000
Mumbai,3.6,India,Asia & Pacific,18.9667,72.8333,23355000
Sao Paulo,3.5,Brazil,South/Latin America,-23.5504,-46.6339,22046000
Berlin,3.5,Germany,Europe,52.5167,13.3833,3644826
Istanbul,3.2,Turkey,Europe,41.0100,28.9603,15154000
Mexico City,3.1,Mexico,South/Latin America,19.4333,-99.1333,20996000
Rio de Janeiro,2.8,Brazil,South/Latin America,-22.9083,-43.1964,12272000
Warsaw,2.6,Poland,Europe,52.2167,21.0333,1790658
Buenos Aires,2.3,Argentina,South/Latin America,-34.5997,-58.3819,16157000
Cape Town,2.2,South Africa,Africa,-33.9250,18.4250,433688
Cairo,2.2,Egypt,Middle east,30.0561,31.2394,19372000
Johannesburg,2.1,South Africa,Africa,-26.2044,28.0416,4434827
Lisbon,2.0,Portugal,Europe,38.7452,-9.1604,506654
Lagos,1.9,Nigeria,Africa,6.4500,3.4000,15279000
Manila,1.9,Philippines,Asia & Pacific,14.5958,120.9772,23088000
Prague,1.6,Czechia,Europe,50.0833,14.4167,1324277