In [48]:
import pandas as pd
import json
with open('data/expatistan/expatistan.json') as f:
    data = json.load(f)

expatistan = pd.json_normalize(data)
expatistan.columns = ['city', 'beer_supermarket', 'cappuccino', 'beer_pub']
expatistan['beer_supermarket'] = expatistan['beer_supermarket'].astype(float)
expatistan['cappuccino'] = expatistan['cappuccino'].astype(float)
expatistan['beer_pub'] = expatistan['beer_pub'].astype(float)
expatistan = expatistan.rename(columns = {"city": "city_ascii"})
# expatistan = expatistan.set_index('city_ascii')

Empty DataFrame
Columns: [city_ascii, beer_supermarket, cappuccino, beer_pub]
Index: []

In [50]:
numbeo_clean = pd.read_csv('data/numbeo/numbeo_clean.csv')
numbeo_clean = numbeo_clean.drop(columns=['Unnamed: 0'])
numbeo_clean.head()

0          Richmond
1      Fort Collins
2            Boston
3          New York
4      Philadelphia
           ...
487           Lorca
488         Sevilla
489           Odesa
490            Kyiv
491    Zaporizhzhia
Name: city_ascii, Length: 492, dtype: object

In [51]:
test = pd.merge(numbeo_clean, expatistan, how="outer", on=["city_ascii"])
test.iloc[100:150]

,city_ascii,admin_name,country,region,bread,beer,coffee,latitude,longitude,population,beer_supermarket,cappuccino,beer_pub
100,Leeds,Leeds,United Kingdom,Europe,1.20,2.99,3.89,53.7997,-1.5492,1901934.0,2.59,3.83,5.16
101,Manama,Al ‘Āşimah,Bahrain,Arab States,1.25,2.99,4.69,26.2167,50.5831,157474.0,3.47,5.46,8.00
102,Luxembourg,Luxembourg,Luxembourg,Europe,2.94,2.99,4.11,49.6106,6.1328,122273.0,NaN,NaN,NaN
103,Luxembourg,Luxembourg,Luxembourg,Europe,2.94,2.99,4.11,49.6106,6.1328,122273.0,2.20,4.75,5.87
104,Petaling Jaya,Selangor,Malaysia,Asia & Pacific,0.95,2.97,2.87,3.1073,101.6067,638516.0,2.70,3.79,4.49
105,Manchester,Manchester,United Kingdom,Europe,1.37,2.97,3.81,53.4794,-2.2453,2705000.0,2.74,4.36,5.43
106,Espoo,Uusimaa,Finland,Europe,2.60,2.95,4.91,60.2100,24.6600,269802.0,NaN,NaN,NaN
107,Aberdeen,Aberdeen City,United Kingdom,Europe,1.23,2.94,3.64,57.1500,-2.1100,214610.0,2.88,3.93,5.23
108,Calgary,Alberta,Canada,North America,2.00,2.91,3.43,51.0500,-114.0667,1239220.0,2.35,3.61,5.96
109,Saskatoon,Saskatchewan,Canada,North America,2.21,2.91,3.49,52.1333,-106.6833,246376.0,2.76,4.08,5.45
110,Vancouver,British Columbia,Canada,North America,2.52,2.91,3.47,49.2500,-123.1000,2264823.0,2.29,4.02,5.22
111,Winnipeg,Manitoba,Canada,North America,1.93,2.90,3.66,49.8844,-97.1464,705244.0,2.99,3.67,4.67
112,Haifa,Haifa,Israel,Europe,2.24,2.90,3.77,32.8000,34.9833,281087.0,2.52,4.49,9.00
113,Victoria,British Columbia,Canada,North America,2.69,2.88,3.57,48.4283,-123.3647,335696.0,3.04,4.08,5.72
114,Surabaya,Jawa Timur,Indonesia,Asia & Pacific,1.19,2.87,2.28,-7.2458,112.7378,4975000.0,2.24,3.65,3.66
115,Cambridge,Cambridgeshire,United Kingdom,Europe,1.57,2.79,3.90,52.2053,0.1192,66.0,2.57,4.18,7.00
116,Grenoble,Auvergne-Rhône-Alpes,France,Europe,1.64,2.77,3.60,45.1715,5.7224,687985.0,2.38,4.24,7.00
117,Dubrovnik,Dubrovačko-Neretvanska Županija,Croatia,Europe,1.69,2.75,3.54,42.6403,18.1083,42615.0,1.24,2.25,3.68
118,Oxford,Oxfordshire,United Kingdom,Europe,1.19,2.75,4.05,51.7519,-1.2578,154600.0,2.51,3.77,6.00
119,Sheffield,Sheffield,United Kingdom,Europe,1.28,2.75,3.73,53.3833,-1.4667,685368.0,1.85,3.79,5.13
120,Jerusalem,Southern,Israel,Europe,1.65,2.74,3.76,31.7833,35.2167,919438.0,3.22,4.21,8.00
121,London,"London, City of",United Kingdom,Europe,1.38,2.73,4.03,51.5072,-0.1275,10979000.0,2.39,4.21,7.00
122,London,Ontario,Canada,North America,1.97,2.54,3.45,42.9836,-81.2497,383822.0,2.39,4.21,7.00
123,Casablanca,Casablanca-Settat,Morocco,Arab States,0.81,2.72,1.80,33.5992,-7.6200,4370000.0,1.72,2.91,5.37
124,Oulu,Pohjois-Pohjanmaa,Finland,Europe,2.06,2.72,3.66,65.0142,25.4719,200526.0,2.40,4.18,5.84
125,Paris,Île-de-France,France,Europe,2.23,2.71,4.47,48.8566,2.3522,11020000.0,2.43,5.52,9.00
126,Jakarta,Jakarta,Indonesia,Asia & Pacific,1.24,2.71,2.23,-6.2146,106.8451,34540000.0,2.63,2.39,3.32
127,Nantes,Pays de la Loire,France,Europe,1.36,2.70,3.22,47.2181,-1.5528,633690.0,2.29,3.05,7.00
128,Quebec City,Quebec,Canada,North America,2.38,2.69,3.10,46.8139,-71.2081,705103.0,2.60,3.46,5.29
129,Tampere,Pirkanmaa,Finland,Europe,2.37,2.66,4.37,61.4981,23.7608,225118.0,2.59,4.92,7.00
130,Toronto,Ontario,Canada,North America,2.23,2.66,3.56,43.7417,-79.3733,5429524.0,2.41,3.73,6.00
131,Edmonton,Alberta,Canada,North America,2.06,2.65,3.57,53.5344,-113.4903,1062643.0,3.07,4.15,5.52
132,Christchurch,Canterbury,New Zealand,Asia & Pacific,1.70,2.65,3.43,-43.5309,172.6365,377200.0,4.56,3.78,8.00
133,Osaka,Ōsaka,Japan,Asia & Pacific,1.88,2.64,3.65,34.6936,135.5019,14977000.0,2.32,4.96,5.09
134,Bristol,"Bristol, City of",United Kingdom,Europe,1.52,2.63,3.79,51.4500,-2.5833,724000.0,2.44,3.80,5.97
135,Kuala Lumpur,Kuala Lumpur,Malaysia,Asia & Pacific,0.80,2.55,2.87,3.1478,101.6953,8285000.0,2.68,3.42,5.90
136,Brampton,Ontario,Canada,North America,1.83,2.53,2.65,43.6833,-79.7667,593638.0,NaN,NaN,NaN
137,Montpellier,Occitanie,France,Europe,1.74,2.49,3.31,43.6119,3.8772,607896.0,2.39,4.27,7.00
138,Gent,Flanders,Belgium,Europe,1.94,2.48,3.53,51.0536,3.7253,262219.0,NaN,NaN,NaN
139,Uppsala,Uppsala,Sweden,Europe,2.92,2.47,4.11,59.8498,17.6389,164535.0,1.98,4.54,7.00
140,Uppsala,Stockholm,Sweden,Europe,2.92,2.47,4.11,59.8601,17.6400,133117.0,1.98,4.54,7.00
141,Mississauga,Ontario,Canada,North America,2.22,2.46,2.84,43.6000,-79.6500,721599.0,1.87,3.34,4.94
142,Exeter,Devon,United Kingdom,Europe,1.19,2.46,3.39,50.7167,-3.5333,124180.0,2.43,3.90,5.85
143,Nagoya,Aichi,Japan,Asia & Pacific,2.06,2.45,3.99,35.1167,136.9333,9113000.0,2.62,4.50,4.69
144,Reading,Reading,United Kingdom,Europe,1.64,2.45,3.37,51.4542,-0.9731,337108.0,NaN,NaN,NaN
145,Seoul,Seoul,South Korea,Asia & Pacific,2.76,2.44,4.34,37.5833,127.0000,21794000.0,2.18,4.27,4.64
146,Edinburgh,"Edinburgh, City of",United Kingdom,Europe,1.37,2.40,3.70,55.9530,-3.1890,488050.0,2.63,4.02,7.00
147,Glasgow,Glasgow City,United Kingdom,Europe,1.16,2.40,3.81,55.8609,-4.2514,985290.0,2.06,3.88,6.00
148,Kitchener,Ontario,Canada,North America,2.21,2.39,2.93,43.4186,-80.4728,470015.0,NaN,NaN,NaN
149,Basel,Basel-Stadt,Switzerland,Europe,3.14,2.37,5.68,47.5606,7.5906,177595.0,3.96,5.83,8.00

In [3]:
expatistan.max()

city                Zurich
beer_supermarket      5.73
cappuccino               7
beer_pub                14
dtype: object

In [4]:
expatistan.describe()

       beer_supermarket  cappuccino    beer_pub
count        414.000000  415.000000  412.000000
mean           1.751304    3.209711    4.099515
std            0.951966    1.275186    2.292285
min            0.160000    0.060000    0.040000
25%            1.032500    2.070000    2.127500
50%            1.550000    3.290000    3.905000
75%            2.287500    4.030000    5.772500
max            5.730000    7.000000   14.000000

In [6]:
cities = pd.read_csv('data/city-data/world-cities-data.csv')
cities.set_index('city_ascii')

,country,region,latitude,longitude,population,iso2,iso3,admin_name,city
city_ascii,,,,,,,,,
Kabul,Afghanistan,Asia & Pacific,34.5328,69.1658,3678034.0,AF,AFG,Kābul,Kabul
Kandahar,Afghanistan,Asia & Pacific,31.6078,65.7053,491500.0,AF,AFG,Kandahār,Kandahār
Herat,Afghanistan,Asia & Pacific,34.3738,62.1792,436300.0,AF,AFG,Herāt,Herāt
Mazar-e Sharif,Afghanistan,Asia & Pacific,36.7000,67.1167,427600.0,AF,AFG,Balkh,Mazār-e Sharīf
Kunduz,Afghanistan,Asia & Pacific,36.7280,68.8725,259809.0,AF,AFG,Kunduz,Kunduz
...,...,...,...,...,...,...,...,...,...
Ruwa,Zimbabwe,Africa,-17.8897,31.2447,22038.0,ZW,ZWE,Mashonaland East,Ruwa
Shamva,Zimbabwe,Africa,-17.3196,31.5700,10317.0,ZW,ZWE,Mashonaland Central,Shamva
Chivhu,Zimbabwe,Africa,-19.0211,30.8922,10263.0,ZW,ZWE,Mashonaland East,Chivhu
Plumtree,Zimbabwe,Africa,-20.4869,27.8042,2148.0,ZW,ZWE,Matabeleland South,Plumtree
Mazoe,Zimbabwe,Africa,-17.5196,30.9700,9966.0,ZW,ZWE,Mashonaland Central,Mazoe

In [11]:
# TODO: not sure how to merge city data into expatistan df correctly? 
new_df = pd.merge(expatistan, cities, how='left', left_on=['city'], right_on=['city_ascii'])
new_df.head(25)

,city_x,beer_supermarket,cappuccino,beer_pub,city_ascii,country,region,latitude,longitude,population,iso2,iso3,admin_name,city_y
0,Kabul,2.61,2.81,5.79,Kabul,Afghanistan,Asia & Pacific,34.5328,69.1658,3678034.0,AF,AFG,Kābul,Kabul
1,Tirana,1.07,1.56,3.58,Tirana,Albania,Europe,41.3300,19.8200,418495.0,AL,ALB,Tiranë,Tirana
2,Algiers,0.88,2.28,2.10,Algiers,Algeria,Arab States,36.7764,3.0586,3415811.0,DZ,DZA,Alger,Algiers
3,Buenos Aires,0.95,2.07,1.91,Buenos Aires,Argentina,South/Latin America,-34.5997,-58.3819,16157000.0,AR,ARG,"Buenos Aires, Ciudad Autónoma de",Buenos Aires
4,Buenos Aires,0.95,2.07,1.91,Buenos Aires,Costa Rica,South/Latin America,9.1497,-83.3334,45000.0,CR,CRI,Puntarenas,Buenos Aires
5,San Juan,0.68,1.78,1.07,San Juan,Argentina,South/Latin America,-31.5375,-68.5364,471389.0,AR,ARG,San Juan,San Juan
6,San Juan,0.68,1.78,1.07,San Juan,Costa Rica,South/Latin America,9.9609,-84.0731,24944.0,CR,CRI,San José,San Juan
7,San Juan,0.68,1.78,1.07,San Juan,Dominican Republic,South/Latin America,18.8070,-71.2290,72950.0,DO,DOM,El Valle,San Juan
8,San Juan,0.68,1.78,1.07,San Juan,Philippines,Asia & Pacific,14.6000,121.0333,122180.0,PH,PHL,San Juan,San Juan
9,San Juan,0.68,1.78,1.07,San Juan,Puerto Rico,South/Latin America,18.4037,-66.0636,331165.0,PR,PRI,Puerto Rico,San Juan
10,San Juan,0.68,1.78,1.07,San Juan,Trinidad And Tobago,South/Latin America,10.6500,-61.4500,13797.0,TT,TTO,San Juan/Laventille,San Juan
11,San Juan,0.68,1.78,1.07,San Juan,United States,North America,26.1903,-98.1520,37008.0,US,USA,Texas,San Juan
12,Santa Rosa,1.16,1.17,2.27,Santa Rosa,Argentina,South/Latin America,-36.6203,-64.2906,103860.0,AR,ARG,La Pampa,Santa Rosa
13,Santa Rosa,1.16,1.17,2.27,Santa Rosa,Brazil,South/Latin America,-27.8708,-54.4814,59281.0,BR,BRA,Rio Grande do Sul,Santa Rosa
14,Santa Rosa,1.16,1.17,2.27,Santa Rosa,Ecuador,South/Latin America,-3.4522,-79.9617,48929.0,EC,ECU,El Oro,Santa Rosa
15,Santa Rosa,1.16,1.17,2.27,Santa Rosa,Philippines,Asia & Pacific,14.3167,121.1167,353767.0,PH,PHL,Laguna,Santa Rosa
16,Santa Rosa,1.16,1.17,2.27,Santa Rosa,United States,North America,38.4458,-122.7067,324634.0,US,USA,California,Santa Rosa
17,Yerevan,0.81,2.24,1.64,Yerevan,Armenia,Europe,40.1814,44.5144,1075800.0,AM,ARM,Yerevan,Yerevan
18,Adelaide,4.22,3.47,6.00,Adelaide,Australia,Asia & Pacific,-34.9289,138.6011,1345777.0,AU,AUS,South Australia,Adelaide
19,Brisbane,4.48,3.77,7.00,Brisbane,Australia,Asia & Pacific,-27.4678,153.0281,2514184.0,AU,AUS,Queensland,Brisbane
20,Canberra,3.70,3.51,7.00,Canberra,Australia,Asia & Pacific,-35.2931,149.1269,426704.0,AU,AUS,Australian Capital Territory,Canberra
21,Darwin,3.43,3.86,5.99,Darwin,Australia,Asia & Pacific,-12.4381,130.8411,136828.0,AU,AUS,Northern Territory,Darwin
22,Gold Coast,5.73,3.76,4.60,Gold Coast,Australia,Asia & Pacific,-28.0167,153.4000,679127.0,AU,AUS,Queensland,Gold Coast
23,Hobart,4.25,3.52,6.00,Hobart,Australia,Asia & Pacific,-42.8806,147.3250,240342.0,AU,AUS,Tasmania,Hobart
24,Hobart,4.25,3.52,6.00,Hobart,United States,North America,41.5139,-87.2729,27939.0,US,USA,Indiana,Hobart